name: "checks"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Prepare circuits
        run: npm run prepare-circuits

      - name: Overwrite circuit files
        run: cp -Rf assets/registerIdentityLight256.dev/* zkit/artifacts/circuits/RegisterIdentityLight256.circom

      - name: Run tests
        run: npm run test
